name: science
on: push

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
        julia-version: [1.8.1]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}    
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Turbospectrum
      uses: actions/checkout@v3
      with:
        repository: bertrandplez/Turbospectrum2019
    
    - name: Compile Turbospectrum
      run: |
        cd Turbospectrum2019/exec-gf-v19.1
        make

    - name: Set up Julia ${{ matrix.julia-version }}
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
        arch: 'x64'
        show-versioninfo: false