name: science
on: push

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
        julia-version: [1.8.1]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}    
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout Turbospectrum
      uses: actions/checkout@v3
      with:
        repository: bertrandplez/Turbospectrum2019
    
    - name: Compile Turbospectrum
      run: |
        ls
        cd exec-gf-v19.1
        make

#    - name: Checkout MOOG
#      uses: actions/checkout@v3
#      with:

    - name: Set up Julia ${{ matrix.julia-version }}
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
        arch: 'x64'
        show-versioninfo: false

    - name: Add Korg
      run: |
        julia -e 'using Pkg; Pkg.add("Korg")'

