name: science
on: push

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest --> gfortran not working on osx yet
        python-version: [3.9]
        julia-version: [1.8.1]
        gcc_v: [9] # Version of GFortran we want to use.
        arch: ['x64']
    env:
      FC: gfortran-${{ matrix.gcc_v }}
      GCC_V: ${{ matrix.gcc_v }}       
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}    
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install GFortran Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-${GCC_V} gfortran-${GCC_V}
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bingcov gcov /usr/bin/gcov-${GCC_V}

    - name: Install GFortran macOS
      if: contains(matrix.os, 'macos')
      run: brew install gcc@${GCC_V} || brew upgrade gcc@${GCC_V} || true

    - name: Checkout Turbospectrum
      uses: actions/checkout@v3
      with:
        repository: bertrandplez/Turbospectrum2019
    
    - name: Compile Turbospectrum
      run: |
        pwd
        cd exec-gf-v19.1
        make
        echo "::add-path::$GITHUB_WORKSPACE"

    - name: Checkout MOOG
      uses: actions/checkout@v3
      with: 
        repository: andycasey/moog17scat
        
    - name: Compile MOOG
      run: |
        pwd
        ls
        make -f Makefile.gh
        echo "::add-path::$GITHUB_WORKSPACE"
    - run: |
        ./MOOGSILENT
        
    - name: Set up Julia ${{ matrix.julia-version }}
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
        arch: ${{ matrix.arch }}
        show-versioninfo: false

    - name: Checkout Korg
      uses: actions/checkout@v3
      with:
        repository: ajwheeler/Korg.jl

    - name: Install Korg
      run: |
        julia -e 'using Pkg; Pkg.add("Korg")'
    
    - name: Check MOOG
      run: |
        MOOGSILENT

    - name: Check Turbospectrum
      run: |
        babsma_lu


    - name: Summary
      run: |
        echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY